<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>c915fbb3-d7ac-413c-b2cb-557c0def3d37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;login&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c11f4b3-56a8-407c-a8a1-7808c72bbecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0ff16207-47c9-4ad7-bd7f-8f29f35d881c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn round btn-block btn-glow btn-bg-gradient-x-purple-blue col-12 mr-1 mb-1</value>
      <webElementGuid>0cc3cd6d-1a43-4249-9153-03541fbe7819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>091e8a30-c356-4d30-b974-c52ae666bde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login
										</value>
      <webElementGuid>a2bc938d-a669-4269-b1fc-f604b2188acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;loaded&quot;]/body[@class=&quot;vertical-layout vertical-menu 1-column  bg-full-screen-image blank-page blank-page  pace-done&quot;]/div[@class=&quot;app-content content&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;content-body&quot;]/section[@class=&quot;flexbox-container&quot;]/div[@class=&quot;col-12 d-flex align-items-center justify-content-center&quot;]/div[@class=&quot;col-lg-4 col-md-6 col-10 box-shadow-2 p-0&quot;]/div[@class=&quot;card border-grey border-lighten-3 px-1 py-1 m-0&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;form-group text-center&quot;]/button[@class=&quot;btn round btn-block btn-glow btn-bg-gradient-x-purple-blue col-12 mr-1 mb-1&quot;]</value>
      <webElementGuid>b735870d-0a22-438d-b1fe-12dc8bb25a24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='login']</value>
      <webElementGuid>6ed37a58-3c8d-4687-8a7b-bec166d6b3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::button[1]</value>
      <webElementGuid>eb85619c-57a8-4193-9ea0-cd67850c29b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>978a03f4-cf2e-47c3-bd49-ef51e5986abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'login' and (text() = 'Login
										' or . = 'Login
										')]</value>
      <webElementGuid>5a063a58-f53f-4b6c-acda-e4df97e20146</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
