<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , rf, , ))_rf</name>
   <tag></tag>
   <elementGuidId>5521cb8e-2d78-4d35-9425-9fce2b92da67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='rf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e3f001d2-d3ec-4bb2-85c1-b1ef21b739c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>7b700a62-0021-42d4-a02d-782081c25957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de8bc604-de91-4efa-a72e-a7448e366aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rf</value>
      <webElementGuid>cfbce3bb-c0d9-4f60-8507-2df32b88b7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rf</value>
      <webElementGuid>fa013024-08e9-469d-b09e-467a513febcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>9db03316-ce1e-4c14-948e-5e9cf8755618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>if(xc==1)sc(this);</value>
      <webElementGuid>f88a038e-380a-40e8-ba96-b1d61d0b4dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rf&quot;)</value>
      <webElementGuid>e93ddf08-08ab-4a89-ac92-23828a2a04c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='rf']</value>
      <webElementGuid>448525fd-101f-4ff7-bed8-32251dc8ee0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7e57cf6d-775f-4770-a8bd-2fca4c20848c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'about:blank' and @name = 'rf' and @id = 'rf']</value>
      <webElementGuid>6f8d33ad-ba87-48e2-8cf4-4cc394777e89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
