<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keep me signed in_user_remember_me</name>
   <tag></tag>
   <elementGuidId>9cf489c1-dbc3-4d0c-9c86-8ac6130aa013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_remember_me</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_remember_me']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58732714-0c3f-43c6-9b8b-70f8b0c3f9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>11a0d21e-5a9b-4474-81d4-5a4baaaa3d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_remember_me</value>
      <webElementGuid>8ee50221-6909-428f-a9e1-573c5f062dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_remember_me</value>
      <webElementGuid>69b0e6ee-1de8-4174-82d6-803898e90846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9c778c01-5cae-400d-9179-7a1d38606415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_remember_me&quot;)</value>
      <webElementGuid>44520f7f-3fa3-4458-87d1-d13bc1f97fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/login2/Page_Zero - Log in/iframe_concat(id(, , rf, , ))_rf</value>
      <webElementGuid>d71a5e2a-8b1a-4310-b09d-4820b0d22910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_remember_me']</value>
      <webElementGuid>c3a8a3b7-6434-43cb-a8ba-600c72673e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div/div[3]/div/input</value>
      <webElementGuid>09cb6431-de28-44e2-bf91-b7a32c891473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>aac1c060-7b0e-4773-b5d1-efc595c63c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'user_remember_me' and @name = 'user_remember_me']</value>
      <webElementGuid>2707d62f-8833-4cd1-b444-4c151b1de451</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
