<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Signin</name>
   <tag></tag>
   <elementGuidId>66609de1-7da8-408c-b238-989b5608eb15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signin_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='signin_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16632052-6976-4f7c-ae80-3bdb412ef92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin_button</value>
      <webElementGuid>f87f4ab8-87b6-4717-ab7e-92ad98de7174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aa38576b-eb8a-4ba0-87e5-b045ed94aa49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signin btn btn-info</value>
      <webElementGuid>fa6d2442-7bf8-4f1f-bd49-a3cbb21b83b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Signin
                            </value>
      <webElementGuid>7e968d4e-9b71-4c58-be55-4d455afc824d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin_button&quot;)</value>
      <webElementGuid>4daad787-818f-4c52-b4bf-00b3a2641c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/object zero bank/Page_Zero - Personal Banking - Loans - Cred_03e923/iframe_concat(id(, , rf, , ))_rf</value>
      <webElementGuid>17183d35-955e-4670-aa86-6282fd2f1a9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='signin_button']</value>
      <webElementGuid>6299de55-8c2b-4bff-b73c-0c80c639dc3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zero Bank'])[1]/following::button[1]</value>
      <webElementGuid>1b30d25d-9438-49ec-aee5-5d76169bd968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>278745fe-ad15-494b-9c48-4183da633ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Banking'])[1]/preceding::button[1]</value>
      <webElementGuid>baf609d8-68d2-4aa3-97fb-121b13182549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Signin']/parent::*</value>
      <webElementGuid>a833deb8-2211-4b53-bef2-8e370a109e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>27a553f7-01e9-4dbd-9a41-2de158320c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'signin_button' and @type = 'button' and (text() = '
                                Signin
                            ' or . = '
                                Signin
                            ')]</value>
      <webElementGuid>a49435ba-79fa-4743-80a8-bead53758962</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
