<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , rf, , ))_rf (1)</name>
   <tag></tag>
   <elementGuidId>56c383e7-7fb5-4ecb-a4bc-f5eb3c31c796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='rf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b392624f-e0ae-4590-a7e6-91c24acab308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>76cc02d4-cff8-4c59-9e1b-62d9d5aeea5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f08acfe6-32e9-4d51-be08-60fc46f3c871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rf</value>
      <webElementGuid>48f33332-b719-4781-aa90-5d6f74a4efb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rf</value>
      <webElementGuid>7ce88a00-588b-41c4-a2c6-eb7c776e2c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c119bea2-a351-4baa-b95a-c542f6f0411a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>if(xc==1)sc(this);</value>
      <webElementGuid>490ff908-ebab-46ef-8a75-6a2626b1fdac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rf&quot;)</value>
      <webElementGuid>2fbc8fee-8d1e-4971-86f2-525c201ca92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/object zero bank/Page_/iframe_concat(id(, , rf, , ))_rf</value>
      <webElementGuid>11105382-0523-40c4-a5c9-04712ba1070a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='rf']</value>
      <webElementGuid>eb556a20-e341-4456-b7e0-fd5778baf401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5cc4bf42-d7ea-459f-a28b-9e79634f5902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'about:blank' and @name = 'rf' and @id = 'rf']</value>
      <webElementGuid>4144d6f1-ea08-4f98-9182-a4a34afe9fb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
