<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , rf, , ))_rf</name>
   <tag></tag>
   <elementGuidId>02972d03-e46f-45bd-b9c4-f45bd08b5c0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='rf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d5027edb-01f7-4a36-ada2-3bbde0d36838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>a2aeb2ab-9ab5-4fb8-b52d-32ba5b479862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2360d746-a580-4174-aefc-a5258c8c2045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rf</value>
      <webElementGuid>56c925ea-ba5f-414b-90e3-f4fae716d7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rf</value>
      <webElementGuid>dddd2d33-5f70-4a72-84fc-9e224af1e7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>2fed2f01-39bf-42a3-a51e-4c497ab3110f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>if(xc==1)sc(this);</value>
      <webElementGuid>d2f0fe41-7d46-4405-be2d-ee3425a233ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rf&quot;)</value>
      <webElementGuid>408f44b3-0e3f-49df-97ae-963f5263a4f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='rf']</value>
      <webElementGuid>6b6c5aaf-348d-4280-b7b1-07a9fb301932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ea13bd86-a585-4304-bc60-83f9b6cbbd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'about:blank' and @name = 'rf' and @id = 'rf']</value>
      <webElementGuid>8aeeedb3-79a5-4b7d-a3ec-58e0610f89cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
