<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keep me signed in_user_remember_me</name>
   <tag></tag>
   <elementGuidId>66dbbc0a-5833-4999-8916-3c0bea935ec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_remember_me</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_remember_me']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0379f67-7459-41f5-b13a-7a6779cfe0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8c09fb54-799c-4767-9170-f6d831ce88d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_remember_me</value>
      <webElementGuid>327611fe-fe09-4fb2-9242-98215d0e0d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_remember_me</value>
      <webElementGuid>b6edda65-9a07-4060-973f-407fce36b043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>62feafd2-5eb9-40bd-b2de-ff64292e83d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_remember_me&quot;)</value>
      <webElementGuid>84008b82-d723-49ec-b4f6-4cfe82f67b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/object zero bank/Page_/iframe_concat(id(, , rf, , ))_rf (1)</value>
      <webElementGuid>4f6f5acf-e733-4510-b2a7-e71114f183ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_remember_me']</value>
      <webElementGuid>601ad843-a118-4114-a40c-507003b936cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div/div[3]/div/input</value>
      <webElementGuid>51604182-1aa3-451d-af29-ec2bc24d2964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>f87cf3d0-9dac-47a9-898e-1f4fafe67407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'user_remember_me' and @name = 'user_remember_me']</value>
      <webElementGuid>09507a80-6242-41f5-911d-ebc1bb227266</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
