<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Signin</name>
   <tag></tag>
   <elementGuidId>f78aa4e0-8237-433e-8b52-81e1b4e3d11e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signin_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='signin_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>19820b08-f3b9-49c5-9098-28e35ff79479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin_button</value>
      <webElementGuid>332e749f-9f0d-48bc-834b-79d8254c4505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>48723766-e515-4d11-b167-19af20f4c92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signin btn btn-info</value>
      <webElementGuid>a9c324fc-058f-4f29-9c54-f1932de63ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Signin
                            </value>
      <webElementGuid>9bd9dec1-4afc-47ef-ac45-4ee6d523874f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin_button&quot;)</value>
      <webElementGuid>72d67d37-842d-4187-b733-74444cef45fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/login2/Page_Zero - Personal Banking - Loans - Cred_03e923/iframe_concat(id(, , rf, , ))_rf</value>
      <webElementGuid>305947ae-b6db-42fe-a797-1f5ca171a996</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='signin_button']</value>
      <webElementGuid>81054aab-bd32-4c81-88ff-2f6cd989faf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zero Bank'])[1]/following::button[1]</value>
      <webElementGuid>584351fd-da7a-4718-a6f8-c2b5197cb04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>89abfbbd-02f5-4ab0-b164-aefd5e836fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Banking'])[1]/preceding::button[1]</value>
      <webElementGuid>4019e6cd-3092-420e-897f-02386d025a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Signin']/parent::*</value>
      <webElementGuid>00af9668-7994-41a9-bf42-4f621d544f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5d7c9c9d-667e-4ee5-bd9b-0a8decda1547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'signin_button' and @type = 'button' and (text() = '
                                Signin
                            ' or . = '
                                Signin
                            ')]</value>
      <webElementGuid>512b2c9e-168b-4899-a998-9f96d935bce1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
