<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , rf, , ))_rf</name>
   <tag></tag>
   <elementGuidId>e014d34a-1cb9-454c-83d2-a102a9500e84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='rf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f39467be-862e-4262-aefd-3f79bd5feb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>80730718-e265-4fe1-8559-5cf4ce951f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa1492c3-5136-490d-892f-0ea9ee2d0bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rf</value>
      <webElementGuid>3a17d9d9-298b-4517-9a81-c112a808763b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rf</value>
      <webElementGuid>55e49472-8fff-4fbb-be29-a31d705a1dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>7d73095d-0ac2-48af-9276-90b390602dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>if(xc==1)sc(this);</value>
      <webElementGuid>bdc6d0bb-4b52-41c3-a9e1-f357131a72a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rf&quot;)</value>
      <webElementGuid>a041a5b1-ee8e-4ee8-a948-89053441f09b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='rf']</value>
      <webElementGuid>814e66f2-b81b-438c-8b84-c382368aa36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>45792d8b-2cef-4ed1-bb9d-992e630c08e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'about:blank' and @name = 'rf' and @id = 'rf']</value>
      <webElementGuid>8c2dabba-7284-4964-9bac-7d14ab493ea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
